server {
    listen 80;
    server_name apartmentbot.duckdns.org;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name apartmentbot.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/apartmentbot.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/apartmentbot.duckdns.org/privkey.pem;

    location /api/ {
        proxy_pass http://api:8000/api/;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}
